import astropy.units as u
import numpy as np


# https://astroquery.readthedocs.io/en/latest/_modules/astroquery/ipac/nexsci/nasa_exoplanet_archive/core.html
UNIT_MAPPER = {
    "--": None,
    "BKJD": None,  # TODO: optionally support mapping columns to Time objects
    "BJD": u.day,
    "D_L": u.pc,
    "D_S": u.pc,
    "micron": u.um,
    "microns": u.um,
    "Earth flux": u.L_sun / (4 * np.pi * u.au**2),
    "Earth Flux": u.L_sun / (4 * np.pi * u.au**2),
    "Fearth": u.L_sun / (4 * np.pi * u.au**2),
    "M_E": u.M_earth,
    "Earth Mass": u.M_earth,
    "Mearth": u.M_earth,
    "M_J": u.M_jupiter,
    "Mjupiter": u.M_jupiter,
    "Jupiter Mass": u.M_jupiter,
    "R_Earth": u.R_earth,  # Add u.R_jupiter
    "Rearth": u.R_earth,
    "Earth Radius": u.R_earth,
    "Jupiter Radius": u.R_jupiter,
    "Rjupiter": u.R_jupiter,
    "Searth": u.L_sun / (4 * np.pi * u.au**2),
    "R_Sun": u.R_sun,
    "Rstar": u.R_sun,
    "a_perp": u.au,
    "arc-sec/year": u.arcsec / u.yr,
    "cm/s**2": u.cm / u.s**2,
    "g/cm**3": u.g / u.cm**3,
    "day": u.day,
    "days": u.day,
    "degrees": u.deg,
    "dexincgs": u.dex(u.cm / u.s**2),
    "hours": u.hr,
    "hour": u.hr,
    "hrs": u.hr,
    "kelvin": u.K,
    "logLsun": u.dex(u.L_sun),
    "log(Lsun)": u.dex(u.L_sun),
    "log(Solar)": u.dex(u.L_sun),
    "mags": u.mag,
    "microas": u.uas,
    "uas": u.uas,
    "perc": u.percent,
    "pi_E": None,
    "pi_EE": None,
    "pi_EN": None,
    "pi_rel": None,
    "ppm": (u.Unit("%") * 1e-6),  # Convert ppm to %, as csm.ppm doesn't seem to work
    "seconds": u.s,
    "deg": u.deg,
    "Solar mass": u.M_sun,
    "solarradius": u.R_sun,
    "Solar Radius": u.R_sun,
    "log10(cm/s**2)": u.dex(u.cm / u.s**2),
    "log(cm/s**2)": u.dex(u.cm / u.s**2),
    "dex": u.dex(None),
    "sexagesimal": None,
}
